name = "MannKendall2"                                                                   
uuid = "778ff4b9-0ba3-4b3e-a982-d971b817e3a7"                                                                      
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
StatsFuns = "0.9"

